/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
/**
 * Copyright (c) 2023, CS 346 Whiteboard App Team 210 Winter 2022.
 * All rights reserved.
 *
 * This code is licensed under the MIT License.
 */

package cs.shared.project

class Shared {
    companion object SysInfo {
        val userName = System.getProperty("user.name")
        val userHome = System.getProperty("user.home")
        val hostname = java.net.InetAddress.getLocalHost().hostName
        val hostAddress = java.net.InetAddress.getLocalHost().hostAddress
        val osName = System.getProperty("os.name")
        val osVersion = System.getProperty("os.version")
        val osArch = System.getProperty("os.arch")
        val processors = Runtime.getRuntime().availableProcessors()
        val freeMemory = Runtime.getRuntime().freeMemory()
        val totalMemory = Runtime.getRuntime().totalMemory()
    }

}

fun main() {
    println("Hello from Shared")
}
